Fix "'findstr' is not recognized as ..."
aeternity/relx pull request #4
Opened 2019-05-23 14:29 UTC by venimus

Styrene overrides the default path variable removing the `Windows\System32` entry which makes `findstr` unavailable when script is executed from the launcher `aeternity.exe` resulting in:

```
'findstr' is not recognized as an internal or external command,
operable program or batch file.
'findstr' is not recognized as an internal or external command,
operable program or batch file.
'findstr' is not recognized as an internal or external command,
operable program or batch file.
./usr/lib/aeternity/bin/aeternity.cmd exited with status 0.
Press return to close this window.
```

2019-05-27 10:26 UTC, dincho commented
related: https://github.com/achadwick/styrene/issues/23

2019-05-29 09:43 UTC, lucafavatella reviewed
What is the way forward for this? Is there a tracked user issue?

I see patch already [included in relx v3.32.0](https://github.com/erlware/relx/commit/ba7be7e3384574019202d3d37366f7fd5e8bf40a).

I see last rebar3 tag i.e. 3.10 [does not include this relx version](https://github.com/erlang/rebar3/blob/3.10.0/rebar.lock#L11) but [it is in rebar3 master](https://github.com/erlang/rebar3/blob/311ba9e48da7c4ef8a681863ef737a597451b8a6/rebar.lock#L11).

2019-05-29 10:29 UTC, dincho commented
@lucafavatella Maybe syncing our relx fork with upstream then pointing our rebar3 to the new commit/version of the fork ?

2019-06-07 13:24 UTC, lucafavatella requested changes
Rejecting as I understand we are rather moving to syncing with / merging upstream.

----

@dincho 

> @lucafavatella Maybe syncing our relx fork with upstream then pointing our rebar3 to the new commit/version of the fork ?
>
> So we have to update it all to the node: relx (upstream update) -> rebar3 (release ?) -> node (update rebar3 binary)

So you mean:
* Merge https://github.com/aeternity/relx/pull/5 (WIP).
* Merge https://github.com/aeternity/rebar3/pull/9 (WIP).
* Release from `aeternity/rebar3`. I suggest doing so so to keep same process regardless of presence of deviations from upstream.
* Update repos `aeternity`, `aesophia`, `docker-builder`.

I need to perform some more testing on those two PRs.

> (TBH: having forks diverting from the upstreams is PITA)

If we wanted to prevent diverting the forks from upstream, we would need to:
* Tag the `aeternity/relx` commits corresponding to the past custom tags of `aeternity/rebar3`.
* Move the `aeternity/rebar3` CI out of the git tree (e.g. in https://github.com/aeternity-bot org? Only scheduled tests run, or would also automated GitHub release upload on tag be possible?).
* Keep no not-force-pushed branch (i.e. branch would have no meaning apart from being the current unstable development; only tags would have meaning). This branch could be named `integration` or `master`.
* Document ^^^ in https://github.com/aeternity/aeternity/wiki/Custom-Rebar3

----

Background below.

This is the `aeternity/relx` repo. It is used by the `aeternity/rebar3` repo, from which a custom version of the `rebar3` build tool is built, that is then used for building some of the Aeternity software - mainly the node. This customization has sometimes been needed for delivering fixes before merged upstream. The overview for this is at https://github.com/aeternity/aeternity/wiki/Custom-Rebar3

The objectives of the current repos/branches setup are:
* (A) Ability to audit what the build tool used for building a past version of the software used to be.
* (B) Ability to deliver build fixes in an effective and efficient manner.

Based on https://github.com/aeternity/aeternity/wiki/Custom-Rebar3 , the projects using this custom `rebar3` version are the following - all referring to a tagged version of this `aeternity/rebar3` repo:
* [`aeternity`](https://github.com/aeternity/aeternity/commit/7f628830d07d33822402524e5996ac8f9ef1d242)
* [`aesophia`](https://github.com/aeternity/aesophia/commit/4e78756b9085179e5284f63233bbbdfca09d92b0)
* [`docker-builder`](https://github.com/aeternity/docker-builder/commit/0d5d88f4b184f7ad3ad118ac167e93a38b702b24#diff-3254677a7917c6c01f55212f86c57fbfR28)

The past tags of this `aeternity/rebar3` repo are at https://github.com/aeternity/rebar3/releases

Notice that the tagged versions at `aeternity/rebar3` refer to non-upstream versions from the `aeternity/relx` repo. Such `aeternity/relx` repo has [no custom tags](https://github.com/aeternity/relx/releases): the commits of `aeternity/relx` referred to by `aeternity/rebar3` (see for example [the relx version](https://github.com/aeternity/relx/commit/ebdcebf135dfe03bec3801e1e1fba0ab1e1b36d0) [used by the last rebar3 tag](https://github.com/aeternity/rebar3/blob/3.9.1-aeternity.2/rebar.lock#L13) ) are kept reachable by the `integration` branch of the `aeternity/relx` repo not being force-pushed.

There are some differences between the custom rebar3 and relx repos and the upstream ones - in particular basic [CI tests](https://github.com/aeternity/rebar3/pull/6/files#diff-1d37e48f9ceff6d8030570cd36286a61) and [automated GitHub release upload](https://github.com/aeternity/rebar3/pull/7/files).

2019-06-07 14:14 UTC, closed without merging